version: "3.8"

services:
  web:
    build: .
    container_name: captchasolved
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
